export enum EntityName {
    User = "user",
    Profile = "profile",
    Otp = "otp",
    Category = "category",
    Address = "address",
    Item = "item",
    ItemImage = "item_image",
    Comment = "comment",
    Cart = "cart",
    Discount = "discount",
    Favorite = "favorite",
    Order = "order",
    OrderItem = "order_item",
    Payment = "payment",
}