export enum EntityName {
  User = 'users',
  Profile = 'profiles',
  Otp = 'otps',
  Category = 'categories',
  Address = 'addresses',
  Item = 'items',
  ItemImage = 'item_images',
  Comment = 'comments',
  Cart = 'carts',
  Discount = 'discounts',
  Favorite = 'favorites',
  Order = 'orders',
  OrderItem = 'order_items',
  Payment = 'payments',
  Contact = 'contacts',
  ContactReply = 'contact_replies',
  RateLimitRecord = 'rate_limit_records',
}
