export enum EntityName {
  USER = "users",
  PROFILE = "profiles",
  OTP = "otps",
  CATEGORY = "categories",
  ADDRESS = "addresses",
  ITEM = "items",
  ITEM_IMAGE = "item_images",
  COMMENT = "comments",
  CART = "carts",
  DISCOUNT = "discounts",
  FAVORITE = "favorites",
  ORDER = "orders",
  ORDER_ITEM = "order_items",
  PAYMENT = "payments",
  CONTACT = "contacts",
  CONTACT_REPLY = "contact_replies",
  RATE_LIMIT_RECORD = "rate_limit_records",
}
